# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'


format = """
$conda\
$python\
$hostname\
$localip\
$username\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$cmd_duration\
$hg_branch\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""


[character]
success_symbol = "[\uf0da](bold green)"
error_symbol = "[\uf0da](bold red)"

[line_break]
disabled = false

[fill]
symbol = ' '

[conda]
format = '\([$symbol$environment]($style)\) ' 
ignore_base = false

[python]
format = '\([${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\) '
symbol = "\ue73c "

[package]
format = '[$symbol$version]($style) '

[lua]
format = '[$symbol($version )]($style)'

[rust]
format = '[$symbol($version )]($style)'
# symbol = "⚙️  " 
symbol = "\ue7a8 " 

[directory]
format = "\uf07b [$path]($style)[$read_only]($read_only_style) "

[username]
format = "\uf007 [$user]($style) "
disabled = false
show_always = true

[hostname]
format = '[$ssh_symbol$hostname]($style) '
style = 'bold dimmed green'
ssh_symbol = "🌎"
ssh_only = false

[swift] 
format = '[$symbol($version )]($style)'

[git_branch]
symbol = "\ue725"
format = "[$symbol $branch(:$remote_branch)]($style) "

[git_status]
conflicted = "≠"
modified = "!$count"
untracked = "?$count"
ahead = "⇡$count"
behind = "⇣$count"
stashed = "$$count"
staged = "+$count"
renamed  = "≫$count"
deleted = "✘$count"


