#!/bin/bash


# Prompt
# --------------------------------------------------------------------

if [ "$PLATFORM" = Linux ]; then
  PS1="\[\e[1;38m\]\u\[\e[1;34m\]@\[\e[0;1;31m\]\H\[\e[0;1;30m\]:"
  PS1="$PS1\[\e[0;38m\]\w\[\e[1;35m\] > \[\e[0m\]"
else
  ### git-prompt
  __git_ps1() { :;}
  if [ -e ~/.git-prompt.sh ]; then
    source ~/.git-prompt.sh
  fi
  PS1='\[\e[34m\]\u\[\e[1;32m\]@\[\e[0;33m\]\h\[\e[0;35m\]:\[\e[1;31m\]\w\[\e[1;30m\]$(__git_ps1)\[\e[1;31m\] > \[\e[0m\]'
fi

export PATH=$HOME/.local/bin:$PATH

### Colored ls
if [ -x /usr/bin/dircolors ]; then
  eval "`dircolors -b`"
  alias ls='ls --color=auto'
  alias grep='grep --color=auto'
elif [ "$PLATFORM" = Darwin ]; then
  alias ls='ls -G'
fi

if [ -f ~/.dotfiles/zsh/aliases.sh ]; then
  source ~/.dotfiles/zsh/aliases.sh
fi

if [ -f ~/.dotfiles/zsh/functions.sh ]; then
  source ~/.dotfiles/zsh/functions.sh
fi

if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi

if [ -d ~/blue ]; then
  export POETRY_CONFIG_DIR=~/blue/.config/pypoetry
  export POETRY_CACHE_DIR=~/blue/.cache/pypoetry
else 
  export POETRY_CONFIG_DIR=~/.config/pypoetry
  export POETRY_CACHE_DIR=~/.cache/pypoetry
fi 



# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
# __conda_setup="$('/Users/dan/opt/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
# if [ $? -eq 0 ]; then
#     eval "$__conda_setup"
# else
#     if [ -f "/Users/dan/opt/anaconda3/etc/profile.d/conda.sh" ]; then
#         . "/Users/dan/opt/anaconda3/etc/profile.d/conda.sh"
#     else
#         export PATH="/Users/dan/opt/anaconda3/bin:$PATH"
#     fi
# fi
# unset __conda_setup
# <<< conda initialize <<<
